name: advent-of-code-2024
dependencies:
  - cookiecutter
  - flake8
  - matplotlib
  - mypy
  - numba
  - numpy
  - pandas
  - pip
  - pyarrow
  - pytest
  - python>=3.11
  - python-lsp-server
  - requests
  - scikit-learn
  - scipy
  - tqdm
  - zstandard
