name: advent-of-code
dependencies:
  - flake8
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - pyarrow
  - pytest
  - python>=3.11
  - python-lsp-server
  - requests
  - scikit-learn
  - scipy
  - zstandard
